#!/usr/bin/env python
import sys
from oct import run_oct


def main(argv=None):
    if argv is None:
        argv = sys.argv
    assert len(argv) == 2
    rf = argv[1]
    run_oct(
        rf, continue_oct=True, g_a_int_min_initial=1.0e-5,
        g_a_int_max=1.0e-1, g_a_int_converged=1.0e-7, use_threads=True,
        scratch_root=None, print_stdout=True, monotonic=False, backtrack=True)


if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.DEBUG)
    sys.exit(main())
